mysite/food/urls.py
from . import views
from django.urls import path

app_name = "food"
urlpatterns = [
    path('', views.IndexClassView.as_view(), name="index"),
    path('<int:pk>/', views.FoodDetail.as_view(), name="detail"),
    path('add', views.create_item.as_view(), name="create_item"),
    path('edit/<int:id>/', views.edit_item, name="edit_item"),
    path('delete/<int:id>/', views.delete_item, name="delete_item"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name="register"),
    path('login/', authentication_views.LoginView.as_view(template_name = "users/login.html"), name="login"),
    path('logout/', authentication_views.LogoutView.as_view(template_name = "users/logout.html"), name="logout" ),
    path('profile/', user_views.profilepage, name="profile"),
]

urlpatterns += [
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_img = models.CharField(max_length=500, default="https://www.theaxebraughing.uk/wp-content/uploads/2020/04/food-placeholder-image.jpg")

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields.related import OneToOneField

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="profilepic.jpg", upload_to="profile_pictures")
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

mysite/food/forms.py
from django import forms
from django.db.models import fields
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["item_name","item_desc", "item_price", "item_img"]

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import fields

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

mysite/food/views.py
from django.forms.forms import Form
from .forms import ItemForm
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Item
from django.template import context, loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

# Create your views here.

# def index(request):
#     item_list = Item.objects.all()
#     template = loader.get_template("food/index.html")
#     context = {
#         'item_list':item_list,
#     }
#     return render(request, 'food/index.html', context)

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'

# def detail(request, item_id):
#     item = Item.objects.get(pk=item_id)
#     context = {
#         'item':item,
#     }
#     return render(request, 'food/detail.html', context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect("food:index")

    return render(request, "food/itemform.html", {"form":form})

class create_item(CreateView):
    model = Item
    fields = ["item_name", "item_desc", "item_price", "item_img"]

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)

def edit_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect("food:index")

    return render(request, "food/item_form.html", {"form":form, "item":item})

def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == "POST":
        item.delete()
        return redirect("food:index")

    return render(request, "food/itemdelete.html", {"item":item} )

mysite/users/views.py
from django.contrib.auth import logout
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm

# Create your views here.

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Welcome {username}, your account is created")
            return redirect("login")
    else:
        form = RegisterForm()
    return render(request, "users/register.html", {"form":form})

@login_required
def profilepage(request):
    return render(request, "users/profile.html")

mysite/food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>

    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>
        <div class="navbar">
            <a href="{% url 'food:create_item' %}" class="nav-item nav-link">Add item</a>
            <a href="#" class="nav-item nav-link">Delete item</a>
            <a href="#" class="nav-item nav-link">View item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
                <a href="{% url 'profile' %}" class="nav-item nav-link">Profile</a>
            {% else %}
                <a href="{% url 'login' %}" class="nav-item nav-link">login</a>
            {% endif %}
        </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}

</body>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</html>

mysite/food/templates/food/detail.html
{% extends "food/base.html" %}

{% block body %}

    <div class="container">
        <div class="row">
           <div class="col-md-6">
                <img height="300px" width="100%" src="{{ object.item_img }}" class="card">
           </div>

           <div class="col-md-6">
                <h1> {{ object.item_name }} </h1>
                <h2> {{ object.item_desc }} </h2>
                <h3> ${{ object.item_price }} </h3>
                <h3> Created by: {{ object.user_name }} </h3>
                <a href="{% url 'food:delete_item' item.id %}">Delete</a>
            </div>
        </div>
    </div>


{% endblock %}

mysite/food/templates/food/index.html
{% extends "food/base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Document</title>
</head>
<body>

    {% block body %}
        {% for item in item_list %}

        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img src="{{ item.item_img }}" class="card" height="150px">
            </div>

            <div class="col-md-4">
                <h3>{{item.item_name}}</h3>
                <h5>{{item.item_desc}}</h5>
                <h6>${{item.item_price}}</h6>
                <h6>{{item.user_name}}</h6>
            </div>

            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
        
        {% endfor %}
    {% endblock %}
</body>
</html>

mysite/food/templates/food/item_form.html
{% extends "food/base.html" %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-4">
                .<div class="card">
                    <div class="card-header bg-info text-white">
                        <div class="card-title">
                            Add Item
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button type="submit" class="btn-info">Add</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mysite/food/templates/food/itemdelete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

mysite/users/templates/users/login.html
{% extends "food/base.html" %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-4">
                .<div class="card">
                    <div class="card-header bg-info text-white">
                        <div class="card-title">
                            Login
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button type="submit" class="btn-info">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mysite/users/templates/users/logout.html
{% extends "food/base.html" %}

{% block body %}
    <h1>You have been logged out!</h1>
{% endblock %}

mysite/users/templates/users/profile.html
{% extends "food/base.html" %}

{% block body %}
    <h1> {{user.username}} </h1>
    <img src="{{ user.profile.image.url }}" height="200px">
{% endblock %}

mysite/users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Signup</button>
</form>